# -*- coding: utf-8 -*-
# Copyright 2016-2017 LasLabs Inc.
# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl.html).

{
    'name': 'Creu Blanca Demo Database',
    'summary': '',
    'version': '10.0.1.0.0',
    'author': 'Eficent, Odoo Community Association (OCA)',
    'category': '',
    'depends': [
        'medical',
        'workflow_plandefinition',
        'product',
        'medical_center',
        'medical_encounter',
        'base',
        'stock',
        'medical_insurance',
        'medical_insurance_sale',
        'medical_encounter_careplan',
        'medical_careplan',
        'medical_request_group',
        'sale',
        'sale_commission',
        'sale_commission_formula',
        'medical_commission',
        'medical_practitioner',
        'medical_procedure',
        'medical_procedure_purchase',
        'medical_careplan_sale',
        'medical_material',
    ],
    'demo': [
        'demo/patient_demo.xml',
        'demo/prova_workflow_types.xml',
        'demo/products_demo.xml',
        'demo/prova_act_def.xml',
        'demo/prova_plan_definition.xml',
        'demo/center_demo.xml',
        'demo/prova_insurance.xml',
        'demo/sale_commission_formula_demo.xml',
        'demo/practitioner_demo.xml',
    ],
    'website': '',
    'licence': 'LGPL-3',
    'installable': True,
    'auto_install': False,
}
