from . import hr_attendance
from . import hr_department
from . import hr_employee
from . import res_partner
from . import hr_job
from . import hr_contract
from . import resource_calendar
from . import res_users
from . import hr_holidays
from . import hr_laboral_category
